version: "3"
services:
  stack-grp16-frontend:
    build:
      context: .
      args:
        backend_ips: $LC_BACKEND_IPS
    image: knusprig/nginx_frontend
    ports:
      - "80:80"
    environment:
      - CC_BACKEND_SERVERS=$LC_BACKEND_IPS
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == stack-grp16-frontend
