version: "3"
services:
  stack-grp16-backend:
    build:
      context: .
    image: knusprig/nginx_backend
    ports:
      - "8000:80"
    volumes:
      - /etc:/hypervisor_etc:ro
    deploy:
      replicas: 5
      restart_policy:
          condition: on-failure
      placement:
        constraints:
          - node.hostname != stack-grp16-frontend
